config/routes.rb
Rails.application.routes.draw do
  get 'contacts/create'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', confirmations: 'confirmations'}
  resources :users, :only => [:show, :edit, :update]

   root 'home#index'
   resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

	mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	 devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :lastname, :username, :code, :birthday, :occupation, :country, :email, :password, :password_confirmation, :avatar) }
  end

  def after_confirmation_path_for(resource_name, resource)
    root_path
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  private

  def after_confirmation_path_for(resource_name, resource)
    root_path
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
  	@contact = Contact.new(contact_params)
  	if @contact.save
      ContactMailer.contact(@contact).deliver_now
      redirect_to root_path, notice: "Message sent"
  		
  	else
  		redirect_to root_path, notice: "Message not sent"
      
  	end
  end

  def contact_params
  	params.require(:contact).permit(:name, :email, :phone, :subject, :content)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@contact = Contact.new
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController  
  respond_to :json

  protected

  def after_sign_up_path_for(resource)
    root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController  
  respond_to :json
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
    end

 def user_params
  	params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/home/about.html.erb
<h1 id="products">About</h1>

app/views/home/index.html.erb
<body>
<header>

<div> <!--Barra de navegacion -->
 	<nav class="navbar navbar-inverse navbar-fixed-top">
  	<div class="container-fluid">
    	<div class="navbar-header">
    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      	<a class="navbar-brand" href="#">Saving Eco</a>
    	</div>
    	<div class="collapse navbar-collapse" id="myNavbar">
	      <ul class="nav navbar-nav navbar-left">
		      <li><a href="#about">About</a></li>
		      <li><a href="#about">Team</a></li>
		      <li><a href="#product">Products</a></li>
		      <li><a href="#">Community</a></li>
		      <li class="active"><a href="#contact">Contact</a></li>
    		</ul>
    <ul class="nav navbar-nav navbar-right">
      <% unless user_signed_in? %>
	      <li><a href="#" class="btn btn-success navbar-btn" data-toggle="modal" data-target="#ModalRegistration"><i class="fa fa-user-plus" aria-hidden="true"></i>Sign up</a></li>
	      <li><a href="#" class="btn btn-success navbar-btn" data-toggle="modal" data-target="#myModal"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a></li>
	  <% else %>
  <div class="dropdown">
  <button class="btn btn-success navbar-btn dropdown-toggle" type="button" data-toggle="dropdown">
    <img style="width: 30px" src="<%= current_user.avatar.url %>" />  - <%= current_user.username %>
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <% if user_signed_in? %>
    <li><%= link_to "Ir a mi perfil", current_user %></li>
    <% end %>
    <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
    <% end %>
  </ul>
</div>      
    </ul>
  	</div>
	</nav>
</div> <!--End Barra de navegacion -->


<div id="myCarousel" class="carousel slide" data-ride="carousel"> <!-- Carousel-->


  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>



  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">

      <img class="img-carousel" id=carousel-img-juli src="<%= image_path('Med.jpg')%>"  alt="Contaminación en Medellín">
          <div class="absolute">
          <h1>¿...Y si pudieramos ser parte de la solución?</h1>
          <button type="button" class="btn btn-primary">DESCUBRE</button>
        </div>
      </div>

    <div class="item">
      <img class="img-carousel" id=carousel-img-juli src="<%= image_path('MiMedellin.jpg')%>" alt="Como quiero a Medellín">
    </div>

    <div class="item">
      <img class="img-carousel" id=carousel-img-juli src="<%= image_path('MiMedellin.jpg')%>" alt="Como quiero a Medellín">
      <div class="carousel-caption">
          <h3>Medellín, Colombia</h3>
          <p>La ciudad de la eterna primavera</p>
        </div>      
    </div>

  </div>

  <!-- Left and right controls -->
  <div></div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <i class="fa fa-c fa-4x fa-caret-square-o-left" aria-hidden="true"></i>
  </a>



  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
  	<i class="fa fa-c fa-4x fa-caret-square-o-right" aria-hidden="true"></i>
	</a>
	</div>
</div><!-- End Carousel-->

</header> 

<section id="parallax1" data-speed="6" data-type="background"> <!--Parallax-->
    <div class="container">gsdgd</div>
</section> <!-- End Parallax-->

<!-- Product Section
==================================================================-->
<section id="product">

 <div class="row">
  <div class="col-sm-4"><img src="<%= image_path('purificador.jpg')%>" width="500" height="400" /></div>
  <div class="col-sm-8">.col-sm-8</div>
</div>

  
</section> <!-- Product Section End -->

<section id="parallax2" data-speed="2" data-type="background"> <!--Parallax-->
    <div class="container"></div>
</section> <!-- End Parallax-->
	
	<!--Tecnic Section
===================================================================-->	
<section>

<p>Explicacion tecnica</p>
  
</section> <!-- Tecnic Section End -->

<section id="parallax3" data-speed="6" data-type="background"> <!--Parallax-->
    <div class="container"></div>
</section> <!-- End Parallax-->

  <!--Profits Section
===================================================================-->  
<section>

<div id="profits" class="container-fluid text-center">
  <h2>BENEFICIOS FISICOS, PSICOLOGICOS Y SOCIALES </h2>
  <h4>Mucho mas que lo que esperabas</h4>
  <br>
  <div class="row slideanim">
    <div class="col-sm-4">
      <i class=" fa-4x fa fa-leaf" aria-hidden="true"></i>
      <h4>CONTRIBUYES AL MEDIO AMBIENTE</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <i class="fa-4x fa fa-users" aria-hidden="true"></i>
      <h4>CONOCES GENTE</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <i class="fa-4x fa fa-bicycle" aria-hidden="true"></i>
      <h4>HACES EJERCICIO</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
  </div>
  <br><br>
  <div class="row slideanim">
    <div class="col-sm-4">
      <i class="fa-4x fa fa-heartbeat" aria-hidden="true"></i>
      <h4>FORTALECES TU CORAZON</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <i class="fa-4x fa fa-smile-o" aria-hidden="true"></i>
      <h4>TE DIVIERTES</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <i class="fa-4x fa fa-bed" aria-hidden="true"></i>
      <h4 style="color:#303030;">ASDFAS</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
  </div>
</div>
  
</section> <!-- Profits Section End -->

<section id="parallax4" data-speed="6" data-type="background"> <!--Parallax-->
    <div class="container"></div>
</section> <!-- End Parallax-->

  <!--Community Section
===================================================================-->  
<section>

<div id="community" class="container-fluid text-center">

<h2>COMUNIDAD</h2>

<div>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In tempus nibh a rhoncus hendrerit. Proin ex mauris, varius dignissim dolor ut, vulputate volutpat turpis. Maecenas vel augue sollicitudin, imperdiet metus ac, eleifend ligula. Suspendisse potenti. Donec at lacinia purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed finibus, lectus vel sodales dictum, mauris augue ultrices augue, non sodales ante enim quis est. Vestibulum auctor, nibh eget pulvinar ultricies, magna dui porta turpis, vitae congue justo est dictum nisl. Ut maximus eleifend sapien, id finibus elit ullamcorper quis. Cras ac elit erat. Suspendisse et mi et lorem lacinia pulvinar a in tortor. Aenean pulvinar metus sed purus semper, non aliquet leo bibendum.</p>
</div>
</div>
  
</section> <!-- Community Section End -->

<!-- Contact Section
==================================================================-->

<section id="contact">
	<div class="container">
    <h1 class="text-center">Contact</h1>
    <h3 class="text-center text-muted">bla bla bla bla </h3>

    <div class="row">
      <div class="col-md-4">
        <h3>Datos de contacto</h3>
        <h4><i class="fa fa-female fa-contact" aria-hidden="true"></i> Julieth Cardona C.</h4>
        <h4><i class="fa fa-mobile fa-contact" aria-hidden="true"></i> 310 440 3341</h4>
        <h4><i class="fa fa-envelope fa-contact" aria-hidden="true"></i> juli-c.c@hotmail.es</h4>
        <h4><i class="fa fa-map-marker fa-contact" aria-hidden="true"></i> Medellín, Colombia</h4>
      </div>

      <div class="col-md-8">
        <div class="form-group" >
        <%= form_for @contact do |f| %>
        <%= f.label :name, :class => "control-label col-lg-2" %>
        <%= f.text_field :name, :class => "form-control" %>
        </div>

        <div class="col-sm-8 form-group" >
        <%= f.label :email, :class => "control-label" %>
        <%= f.text_field :email, :class => "form-control" %>
        </div>
        
        <div class="col-sm-4 form-group" >
      	<%= f.label :phone, :class => "control-label" %>
      	<%= f.text_field :phone, :class => "form-control" %>
        </div>
        
        
        <div class="form-group">
      	<%= f.label :content, :class => "control-label col-lg-2" %>
      	<%= f.text_area :content, size:"50x5", :class => "form-control" %>
        </div>
        
        <div class="form-group">
          <div class="col-lg-offset-2 col-lg-10">
    	  <%= f.submit 'Send', :class => "btn pull-right" %>
        <% end %>
          </div>
        </div> 
      </div>
    </div>
  </div> 
</section>

<footer class="text-center">
  <a class="up-arrow" href="#myCarousel" data-toggle="tooltip" title="TO TOP">
    <i class="fa fa-2x fa-home" aria-hidden="true"></i>
  </a><br><br>
  <p>Julieth Cardona Ceballos</p>
</footer>

          

</body>
</html>

app/views/home/products.html.erb
<h1 id="products">About</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="Author" content="Julieth Cardona C">
<meta name="Keywords" content="">
<meta name="Description" content="">

  <title>Saving Eco</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>




<%= yield %>

<%= render partial: 'partials/login' %>
<%= render partial: 'partials/registration' %>

</body>
</html>

app/views/partials/_login.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'partials/login_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_login_form.html.erb
<%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
  <div class="alert alert-danger errors" style="display: none"></div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Log in", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/partials/_registration.html.erb
<div class="modal fade" id="ModalRegistration" tabindex="-1" role="dialog" aria-labelledby="ModalRegistrationLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="ModalRegistrationLabel">Sign up</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'partials/registration_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_registration_form.html.erb
<%= form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
  <div class="alert alert-danger errors" style="display: none"></div>

   <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select(:birthday, :start_year => 1940) %>
  </div>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :country %><br />
    <%= f.country_select :country %>
  </div><br>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Hola <%= @user.username  %></h1>

<%= form_for(@user, multipart: true) do |f| %>

   <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select(:birthday, :start_year => 1940) %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :country %><br />
    <%= f.country_select :country %>
  </div><br>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Hola <%= @user.username %> actualiza tus datos! </h1>

<%= link_to "Actualizar", edit_user_path %>